[build]
    functions = "functions"
# Add from here
[[redirects]]
  from = "/index.m3u8"
  to = "/.netlify/functions/redirect"
  status = 200

# 保留原有通配符规则（需放在后面）
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200